CREATE TABLE IF NOT EXISTS colleges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    major VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    enrollment_date DATE NOT NULL,
    graduated BOOLEAN NOT NULL DEFAULT FALSE,
    tuition DECIMAL(10, 2) NOT NULL DEFAULT 0
);
